### ISSUE TITLE
Register services 

### ISSUE THREAD

**Issue by janisz** [CiscoCloud/marathon-consul#17]
Hi

With @dankraw we are working on registering tasks based on Marathon events. Basically this means merging functionality of mesos-consul to marathon-consul. Are you interested in this feature or we should make it stand-alone application. We are using lot of your code, and development takes place [here](https://github.com/janisz/marathon-consul/pull/1)

**Comment by stevendborrelli** [comment]
@janisz @dankraw as we've started to use traefik for our proxies, we don't have the time to devote to this project. Would you be interested in having your fork become the definitive version? We'd put a deprecation notice on ours and point to yours.

**Comment by janisz** [comment]
@stevendborrelli We decided to create a simple tool just for registering Marathon tasks as Consul services, so KV bridge functionality was removed. Final code is moved [here](https://github.com/allegro/marathon-consul).

Thanks
