### ISSUE TITLE
mesos-consul vs. marathon-consul

### ISSUE THREAD

**Issue by hcavalle** [CiscoCloud/marathon-consul#23]
Hello,
Great contributions to the mesos ecosystem here with mantl and the consul / general hashi-\* tooling. Thanks! I notice that the `mesos-consul` project seems to be much more update and have more activity, is it replacing this project entirely?

**Comment by stevendborrelli** [comment]
Yes, since we started to use traefik for load balancing we no longer use haproxy or marathon-consul.
